fileName: spurious_signal_2D.root
histoName: myy_mjj_2D_LM_B

myy_min: 105.0
myy_max: 160.0
n_bins_yy: 55

mjj_min: 80.0
mjj_max: 180.0
n_bins_jj: 20

mjjWS: HH_total_mjj_DSCB_WS.root
mjjWSname: combWS
mjjPDF: cb_C2
mjjSubtractionRange: 1.0

myyWS: HH_total_myy_DSCB_WS.root
myyWSname: combWS
myyPDF: cb_C2
peakPositionName: muCB_C2
myySubtractionRange: 0.15

bkgMyyPDF:
  E1: "Exponential::bkg_myy(myy, lambda_a_myy[-0.1,-5.0,0.0])"
  E2: "EXPR::bkg_myy('exp(@1*(@0-100)/100.0 + @2*(@0-100)*(@0-100)/10000.0)', myy, myy_exppol2_par0[-0.0025,-100.,100.],myy_exppol2_par1[-0.02,-100,100.])"

bkgMjjPDF:
  E1: "Exponential::bkg_mjj(mjj, lambda_a_mjj[-0.1,-5.0,0.0])"
  E2: "EXPR::bkg_mjj('exp(@1*(@0-100)/100.0 + @2*(@0-100)*(@0-100)/10000.0)', mjj, mjj_exppol2_par0[-0.0025,-100.,100.],mjj_exppol2_par1[-0.02,-100,100.])"
  E3: "EXPR::bkg_mjj('exp(@1*(@0-100)/100.0 + @2*(@0-100)*(@0-100)/10000.0 + @3*(@0-100)*(@0-100)*(@0-100)/1000000.0)', mjj, bkg_exppol3_par0[-0.0025,-100.,100.],bkg_exppol3_par1[-0.02,-100,100.],bkg_exppol3_par2[-0.02,-100,100.])"
  B2: "RooBernstein::bkg_mjj(mjj, {bkg_poly2_par0[1], bkg_poly2_par1[0.1,0,1000], bkg_poly2_par2[0,0,1000]})"